#!/usr/bin/env bash

split() {
  local IFS=.
  set -- $1
  echo $@
}

len() {
  echo ${#@}
}

isvalidip() {
  local s=$( split $1 )
  local l=$( len $s )
  if [ $l -ne 4 ] ; then
    return 1
  fi
  for i in $s ; do
    if [ "$i" != "${i//[!0-9]/}" ] || [ "$i" -gt 255 ] ; then
      return 1
    fi
  done
  return 0
}


