#!/usr/bin/env bash

case $# in
  2) ;;
  *) printf "%s\n" "Expecting exactly two arguments" >&2
     exit 1
     ;;
esac

case $1 in
  *[!0-9]*) printf "%s\n" "First argument needs to be a number" >&2
            exit 1
            ;;
esac

for (( i=1; i<=$1; i++)); do
   printf "%6d.%-6d\n" "$RANDOM" "$RANDOM" >> $2
done
