#!/usr/bin/env bash

#:  Title: get command execution time stored in variables
#:   Date: 19.09.2014
#: Author: Vasily Kartashov
#:  Notes: Creates three variables
#:         - real
#:         - user
#:         - system

timev()
{
  local TIMEFORMAT="real=%E user=%U system=%S"
  { local s=$( { time $@ 1>&3- 2>&4-; } 2>&1 ); } 3>&1 4>&2
  eval $s
}
